swyp3-babpool/babpool-backend

src/main/java/com/swyp3/babpool/domain/user/dao/UserRepository.java, src/main/java/com/swyp3/babpool/domain/user/domain/User.java, src/main/java/com/swyp3/babpool/domain/user/domain/UserRole.java, src/main/java/com/swyp3/babpool/domain/user/domain/UserStatus.java, src/main/java/com/swyp3/babpool/infra/auth/AuthJwtParser.java, src/main/java/com/swyp3/babpool/infra/auth/PublicKeyGenerator.java, src/main/java/com/swyp3/babpool/infra/auth/controller/AuthController.java, src/main/java/com/swyp3/babpool/infra/auth/dao/AuthRepository.java, src/main/java/com/swyp3/babpool/infra/auth/domain/Auth.java, src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoMemberProvider.java, src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoPlatformMemberResponse.java, src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoPublicKeys.java, src/main/java/com/swyp3/babpool/infra/auth/request/LoginRequestDTO.java, src/main/java/com/swyp3/babpool/infra/auth/response/AuthMemberResponse.java, src/main/java/com/swyp3/babpool/infra/auth/response/LoginResponseDTO.java, src/main/java/com/swyp3/babpool/infra/auth/service/AuthService.java, src/main/resources/mapper/AuthMapper.xml, src/main/resources/mapper/UserMapper.xml
Resolves #9
- 프론트로부터 받은 idToken으로 이미 회원가입되어있는 회원인지, 회원가입이 필요한 회원인지 응답
- DTO 추가
- LoginResponseDTO : userid(후에 userUUID로 변환 예정), accessToken, isRegistered(회원가입 여부)
- LoginRequestDTO : 소셜로그인 플랫폼명, idToken 값
- 회원 정보 조회 및 저장을 위한 클래스 생성
- User, Auth 도메인
- User, Auth Repository
- User, Auth mapper 파일
- Enum 클래스 추가
- UserStatus, UserRole
추가적으로 예외 처리와 accessToken과 refreshToken을 적용한 응답을 구현해야합니다.  
- 
---
=> feat(auth): Add social login logic

src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java, src/main/java/com/swyp3/babpool/domain/profile/api/ProfilePermitApi.java, src/main/java/com/swyp3/babpool/domain/profile/api/request/ProfileListRequest.java, src/main/java/com/swyp3/babpool/domain/profile/api/request/ProfileUpdateRequest.java, src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java, src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java, src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileResponse.java, src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileUpdateResponse.java, src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java, src/main/java/com/swyp3/babpool/domain/profile/domain/Profile.java, src/main/java/com/swyp3/babpool/domain/profile/exception/ProfileException.java, src/main/java/com/swyp3/babpool/domain/profile/exception/errorcode/ProfileErrorCode.java, src/main/java/com/swyp3/babpool/domain/profile/exception/handler/ProfileExceptionHandler.java, src/main/resources/mapper/ProfileMapper.xml
Resolves #없음
- profile 도메인 하위에서 사용할 전반적인 구조를 추가했습니다.
- 기획을 근거하여 `"/api/profile/list"` 요청은 검증 없이 허용됩니다.
- 화면정의서에 근거하여 프로필 이미지 변경과 그 외 텍스트 정보 변경을 하나의 API 으로  요청받아 처리합니다.
- response 에서 유저 식별 값 반환이 필요한 경우 `userId`(내부 식별 값) 가 아닌 `userUuid`(외부 식별 값) 를 반환하도록 구현했습니다.
- 주석 처리 된 `AwsS3Uploader` 는 별도의 `feature/s3` 브랜치에서 PR 요청 드리겠습니다.
- Mapper 의 쿼리는 작성되어 있지 않습니다.
- 추후 `ProfileService` 클래스의 `saveProfileInfo` 메서드를 구현 부탁드립니다.
---
=> feat(profile): Add overall structure of the profile domain

build.gradle, src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java, src/main/java/com/swyp3/babpool/global/config/WebMvcInterceptJwtConfig.java, src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckS3Api.java, src/main/java/com/swyp3/babpool/infra/s3/application/AwsS3Provider.java, src/main/java/com/swyp3/babpool/infra/s3/config/S3Config.java, src/main/java/com/swyp3/babpool/infra/s3/exception/AwsS3ErrorCode.java, src/main/java/com/swyp3/babpool/infra/s3/exception/AwsS3Exception.java, src/main/java/com/swyp3/babpool/infra/s3/exception/AwsS3ExceptionHandler.java, src/test/java/com/swyp3/babpool/infra/s3/application/AwsS3ProviderTest.java
Resolves #없음
- AWS S3 bucket 이미지 업로드 및 삭제 기능 구현
- `AwsS3Provider` 클래스에 `uploadImage` 메서드와 `deleteImage` 메서드를 구현했습니다.
- 이미지 업로드 과정에서, 파일 확장자와 최대 파일 크기를 검증했습니다.
- 파일 명 중복 방지를 위해 생성 시간 기반 UUID 를 생성해 파일 명을 생성했습니다.
해당 부분을 중점으로 리뷰를 부탁드립니다.
- 이미지 삭제 시, 데이터베이스에 저장된 이미지 URL 을 활용해 삭제하기 때문에 S3 bucket에 해당 이미지 파일이 실존하는지 검증 과정을 포함하지 않았습니다. 혹여 결함이 발생할 수 있는 상황이 있을까요? 
- 이미지 삭제 시, URL에서 파일 명을 추출하는 코드가 의도한 대로 동작하지 않을 가능성이 있을까요? 
- [해당 링크](https://blog.naver.com/btdays/220655060962)와 같이 사용자가 파일명에 `/` 문자를 포함할 경우
---
=> feat(s3): Add s3 image upload and delete feature

.github/workflows/github-actions-server.yaml
- application.yml 설정파일을 하나의 파일로 통합함에 따라 워크플로우 변경
- `application-test.yml` 파일을 생성하지 않도록 수정
- 깃헙 시크릿 value 수정
-
---
=> chore(workflow): Update github actions workflow

src/main/java/com/swyp3/babpool/domain/profile/api/ProfilePermitApi.java, src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfilePagingResponse.java, src/main/java/com/swyp3/babpool/domain/profile/config/PagingSortTypeMappingConfig.java, src/main/java/com/swyp3/babpool/domain/profile/domain/ProfileSortType.java, src/main/resources/mapper/ProfileMapper.xml
Resolves #35 #36 
- 프로필 리스트 페이징 시, 최근 수정된 프로필 순으로 정렬이 기본 설정이 되도록 수정.
- 페이징 쿼리 수정
- `@SortDefault` 어노테이션을 API 파라미터에 추가.
- ProfileMapper.xml 에서 WHERE 절의 OR 연산을 괄호로 묶어 먼저 수행되도록 쿼리 수정.
- 프로필 수정 일자를 페이징 응답에 포함
- [PagingSortTypeMappingConfig.java](https://github.com/swyp3-babpool/babpool-backend/pull/39/files#diff-09c0491c126ffc85d0f8e3b24f7925debae2ac068379297c651bdc6961d1aeb5) 설정 파일을 만들어 프론트가 데이터베이스 테이블의 컬럼명이 아닌, 특정 정렬 기준 명을 서버로 전달했을 때, 올바르게 컬럼명으로 변환되도록 구현
- 특정 정렬 기준과 컬럼명 매핑을 위해 `ProfileSortType` Enum 을 추가
- [Pageable의 sort 값 변경 코드 참고 링크](https://stackoverflow.com/questions/68270814/spring-pageable-sort-change-name-of-property)
---
=> feat(profile): Add paging sort type recent profile modify date as default

src/main/java/com/swyp3/babpool/global/config/WebMvcInterceptJwtConfig.java, src/main/java/com/swyp3/babpool/global/uuid/dao/UserUuidRepository.java, src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckApi.java, src/test/java/com/swyp3/babpool/global/uuid/application/UuidServiceV7Test.java
Resolves #없음
- UuidRepository의 `findByUserUuIdBytes` 메서드 수행 시, `userUuid`가 Mapper 의 매개변수로 바인딩 되지 않음
- `@Param` 어노테이션을 추가해 매개변수 명을 명시.
- 해당 어노테이션이 없어도 정상 동작하는 제 환경과 달리, @yeonjookang 님 환경에서는 동작하지 않음.
- 위와 같이 xml 파일에 빨간 밑줄과 `unable to resolve table` 메시지가 IDE에 나타나는 것이 정상 동작하지 않은 원인일 가능성이 있음. 더 조사 필요.
- [참고 링크 : 인텔리제이 문의 게시판](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360007103039--Solved-Unable-to-resolve-table-name)
---
=> fix(uuid): Update uui repository add param annotation to specifiy parameter

src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java, src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java, src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java, src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentHistoryDoneResponse.java, src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentHistoryRefuseResponse.java, src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java, src/main/java/com/swyp3/babpool/domain/appointment/exception/eoorcode/AppointmentErrorCode.java, src/main/java/com/swyp3/babpool/domain/profile/config/PagingSortTypeMappingConfig.java, src/main/java/com/swyp3/babpool/domain/profile/domain/ProfileSortType.java, src/main/java/com/swyp3/babpool/domain/review/api/ReviewApi.java, src/main/java/com/swyp3/babpool/domain/review/api/request/ReviewCreateRequest.java, src/main/java/com/swyp3/babpool/domain/review/api/request/ReviewUpdateRequest.java, src/main/java/com/swyp3/babpool/domain/review/application/ReviewService.java, src/main/java/com/swyp3/babpool/domain/review/application/ReviewServiceImpl.java, src/main/java/com/swyp3/babpool/domain/review/application/response/ReviewCountByTypeResponse.java, src/main/java/com/swyp3/babpool/domain/review/application/response/ReviewPagingResponse.java, src/main/java/com/swyp3/babpool/domain/review/application/response/ReviewSaveResponse.java, src/main/java/com/swyp3/babpool/domain/review/dao/ReviewRepository.java, src/main/java/com/swyp3/babpool/domain/review/domain/Review.java, src/main/java/com/swyp3/babpool/domain/review/exception/ReviewErrorCode.java, src/main/java/com/swyp3/babpool/domain/review/exception/ReviewException.java, src/main/java/com/swyp3/babpool/domain/review/exception/ReviewExceptionHandler.java, src/main/resources/mapper/AppointmentMapper.xml, src/main/resources/mapper/ReviewMapper.xml
Resolves #51  
- 리뷰 도메인 기능 구현 및 밥약 히스토리 기능 구현
밥약 히스토리 API 추가
- `/api/appointment/list/done` : 완료된 밥약 히스토리 조회
- `reviewRequired` 필드를 통해 리뷰가 필요한 히스토리를 분류할 수 있습니다.
- `/api/appointment/list/refuse`: 거절(시간만료 및 사용자 거절)된 밥약 히스토리 조회
- `refuseType` 필드를 통해 거절 사유(시간만료/사용자 거절)를 분류할 수 있습니다.
[AppointmentServiceImpl.java](https://github.com/swyp3-babpool/babpool-backend/pull/55/files#diff-b241852ec1439106c30757165de244bf248d7f92e7f2c547afb9158a15d6a69a)
- 조회된 밥약 히스토리가 없는 경우 에러 응답을 반환하도록 구현했습니다.
리뷰 API 추가
- `/api/review/list` : 특정 프로필이 받은 모든 리뷰를 조회할 수 있습니다.
- `/api/review/{profileId}/count` : 특정 프로필이 받은 리뷰 종류별 개수를 조회할 수 있습니다.
- `/api/review/create` : 새로운 리뷰 작성을 요청합니다.
- `/api/review/{appointmentId}` : 특정 리뷰에 대한 상세 정보를 조회합니다.
- `/api/review/update` : 작성한 리뷰 수정을 요청합니다. …
=> feat(review, appointment): Add features to resolve #51, appointment history

src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java, src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java, src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java, src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfilePagingResponse.java, src/main/java/com/swyp3/babpool/domain/user/api/UserSignOutApi.java, src/main/java/com/swyp3/babpool/global/jwt/application/JwtServiceImpl.java, src/main/java/com/swyp3/babpool/infra/s3/application/AwsS3Provider.java
Resolves #74 
- profile과 signout 범위에서 코드를 개선했습니다.
- 프로필 페이징 리스트 응답 시, userId가 응답에 포함된 오류를 해결했습니다.
- 사용자 로그아웃 시, refreshToken 쿠키를 클라이언트 측에서 제거되기 위해 maxAge 0 의 쿠키를 응답하도록 변경했습니다.
- 프로필 이미지 수정 시, 기존에 존재하는 프로필 이미지 URL 이 밥풀 서비스의 S3 버켓에 저장된 이미지라면 삭제 처리 후 새 이미지 파일이 업로드 되도록 구현 로직을 수정했습니다.
- maxAge 0 쿠키를 응답하면, 올바르게 사용자 측에서 쿠키가 삭제되는 것이 맞는지 확인 받고 싶습니다.
---
=> refactor(profile, signout): Update profile list response field, Update signout response, Update profile image update logic

src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java, src/main/java/com/swyp3/babpool/domain/appointment/api/request/AppointmentRefuseRequest.java, src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java, src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java, src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentRefuseResponse.java, src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java, src/main/java/com/swyp3/babpool/domain/appointment/domain/AppointmentRefuseMessage.java, src/main/java/com/swyp3/babpool/domain/appointment/exception/eoorcode/AppointmentErrorCode.java, src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java, src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java, src/main/resources/mapper/AppointmentMapper.xml
Resolves #72 
- 밥약 거절 시 DB 업데이트 및 거절 알림 전송
- @Transactional 적용
- 이전에 UserServiceImpl, ProfileServiceImpl에도 적용안한 메소드가 있어서 적용했습니다.
@proHyundo 님께 질문드립니다!!
- modifyDate를 LocalDate.now()를 이용해 직접 업데이트를 해주었는데, myBatis에서 자동으로 하는 방법이 있는지 궁금합니다.
- 응답으로 줄 데이터가 없어서 okMessage를 내려주었는데 어떻게 생각하시는지 궁금합니다.
- 해당 api를 요청한 경우는 사용자가 직접 거절 버튼을 누른 경우인데, 요청이 만료되어 거절되는 경우는 별도의 api를 만들어야하는 건지 궁금합니다.
- 
---
=> Feat: refuse appointment

src/main/java/com/swyp3/babpool/BabpoolApplication.java, src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java, src/main/java/com/swyp3/babpool/global/config/AppointmentSchedulerConfig.java, src/main/resources/mapper/AppointmentMapper.xml
Resolves #없음
- 밥약 요청을 받은 경우 24시간 이내에 수락/거절하지 않으면 appointment_status를 EXPIRE 으로 업데이트 되어야 합니다.
- 스프링 부트 스케줄러를 사용해 해당 이슈를 해결했습니다.
- 스케줄러를 사용하기 위해 `BabpoolApplication` 클래스에 `@EnableScheduling` 어노테이션이 추가되었습니다.
- 1시간 마다 업데이트를 위한 쿼리를 수행하며, 애플리케이션이 부팅되는 시간을 고려해 초기 1분 딜레이를 설정했습니다.
- [참고한 링크 : [Spring Boot] @Scheduled를 이용한 스케쥴러 구현하기](https://velog.io/@developer_khj/Spring-Boot-Scheduler-Scheduled)
---
=> feat(scheduler): Add scheduler for appointment status to expire automatically

src/main/resources/mapper/AppointmentMapper.xml
Resolves #없음
- 약속 수락 시, 사용자가 활성화 해둔 일정/시간을 삭제하려 했으나 외래키에 의해 삭제 불가했습니다.
- on delete cascade 또는 set null 설정을 주는 것은 `t_appointment` 테이블에 `appointment_time_id` 속성의 존재 의미가 사라집니다.
- 따라서 가장 적은 변경으로 해당 문제를 해결하기 위해서, 특정 사용자에게 요청 가능한 일정/시간을 조회하는 SELECT 쿼리를 개선할 필요가 있었습니다.
- AND appoint.appointment_id IS NULL 조건의 필요성 이 조건은 LEFT JOIN을 사용하여 t_appointment 테이블과 조인했을 때 사용됩니다. LEFT JOIN을 통해, t_possible_time 테이블의 possible_time_id와 일치하면서 appointment_status가 "ACCEPT"인 t_appointment 테이블의 행을 조인합니다. 그러나, 우리의 목적은 "ACCEPT" 상태인 약속을 제외하는 것이기 때문에, 조인된 결과에서 실제로 "ACCEPT" 상태인 행이 존재하는 경우 해당 possible_time_id를 결과에서 제외해야 합니다. appoint.appointment_id IS NULL 조건은 t_appointment 테이블과의 조인으로 인해 추가된 행들 중에서 appointment_id 필드가 NULL인 행, 즉 t_possible_time 테이블의 possible_time_id에 대응하는 "ACCEPT" 상태의 약속이 t_appointment 테이블에 존재하지 않는 경우만 결과에 …
=> refactor(appointment): Update findAppointmentPossibleDateTimeByProfil… query

build.gradle, src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java, src/main/java/com/swyp3/babpool/domain/user/api/UserApi.java, src/main/java/com/swyp3/babpool/domain/user/api/UserSignOutApi.java, src/main/java/com/swyp3/babpool/domain/user/application/UserService.java, src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java, src/main/java/com/swyp3/babpool/domain/user/dao/ExitInfoRepository.java, src/main/java/com/swyp3/babpool/domain/user/dao/UserRepository.java, src/main/java/com/swyp3/babpool/domain/user/domain/UserStatus.java, src/main/java/com/swyp3/babpool/domain/user/exception/SignDownException.java, src/main/java/com/swyp3/babpool/domain/user/exception/errorcode/SignDownExceptionErrorCode.java, src/main/java/com/swyp3/babpool/global/common/response/CookieProvider.java, src/main/java/com/swyp3/babpool/global/jwt/JwtAuthenticator.java, src/main/java/com/swyp3/babpool/infra/auth/dao/AuthRepository.java, src/main/java/com/swyp3/babpool/infra/auth/exception/errorcode/AuthExceptionErrorCode.java, src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoProvider.java, src/main/java/com/swyp3/babpool/infra/auth/service/AuthService.java, src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckApi.java, src/main/resources/mapper/AuthMapper.xml, src/main/resources/mapper/ExitInfoMapper.xml, src/main/resources/mapper/UserMapper.xml
Resolves #92 #93
- 로그아웃 및 회원탈퇴 기능이 추가되었습니다.
- 카카오 서버와 통신을 하기 위한 도구로 WebClient 를 선정했고, 이를 위해 webflux 를 추가했습니다.
- [KakaoProvider.java](https://github.com/swyp3-babpool/babpool-backend/pull/98/files#diff-288edb1658cf0881663992b5e670c7b67583ce75d979efd6751cd271427719b6) 파일에 카카오 서비스로부터 로그아웃을 담당하는 `kakaoMemberSignOut` 메서드와 밥풀서비스와 카카오 서비스의 연결끊기를 담당하는 `kakaoMemberDisconnect` 메서드를 추가하였고 로컬환경에서 정상 동작하는 것을 확인했습니다.
- 기존 쿠키 저장 방식이 올바르게 브라우저에 전달되지 않는 것으로 파악되어, 쿠키를 응답하는 API에서만 `ResponseEntity<ApiResponse<>>`를 사용하도록 변경했습니다.
- 기존 코드는 주석처리했습니다. 운영서버에서 정상 동작하는 것을 확인 후 삭제될 예정입니다.
- Controller가 쿠키 설정값들을 의존하고 있지 않기 위해 별도의 [CookieProvider.java](https://github.com/swyp3-babpool/babpool-backend/pull/98/files#diff-f1b59c3e3fbfe0b635bfc6ac4abee57c3fd7982531729bf158fc8a3f913b10ba)를 생성했습니다.
- 운영서버에서 정상 동작하는 것을 확인 후 …
=> feat: Add sign out and sign down

src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java, src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java, src/main/java/com/swyp3/babpool/domain/user/api/UserApi.java, src/main/resources/mapper/ProfileMapper.xml
- ProfileMapper.xml 에 `updateProfileActiveFlag` 메서드가 누락되어 있음
- 사용자 프로필 활성화 여부를 변경하는 쿼리메서드를 추가했습니다
- @yeonjookang `LoginResponseDTO` 타입이 정의되어 있지 않아서 [UserApi.java](https://github.com/swyp3-babpool/babpool-backend/pull/120/files#diff-d5c3f7acdb87c3390b7e64e2e11ffb45da0dbfb45836753e447f93611a560fa6) 에서 컴파일 에러가 발생하고 있었습니다. 우선 `LoginResponse`으로 재수정해서 PR 생성했습니다! 변경이 필요하신게 맞다면 다음 PR에서 수정해주세요 :)
---
=> feat(profile): Add active flag update query in profileMaper

src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java, src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java, src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java, src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java, src/main/resources/mapper/AppointmentMapper.xml
1) 밥약 히스토리에서 응답되는 데이터가 반대로 되어 있다. 거절당한게 나와야 하는데, 내가 거절한게 응답된다.
2)밥약 알림 - 알림 리스트 응답할 때 쿼리에 ASC DESC 다시 확인, 최근 생성일 순으로 응답해야함
1) 쿼리 수정 완료
2) 쿼리에 ORDER BY 속성 추가 완료
- 
---
=> fix: refused history and appointment list orderby

.github/workflows/github-actions-server.yaml, src/main/resources/logback-spring.xml
- github actions build 과정에서 다음과 같이 `/var/logs` 경로에 파일을 생성하지 못하는 오류가 발생 
- github actions는 runners docker 컨테이너 기반으로 동작한다.
- 절대경로를 사용했기 때문에 권한 문제로 해당 경로에 파일을 생성하지 못한것으로 추정해 상대경로로 path를 변경했다.
- 
---
=> Fix: change path of log file

.github/workflows/github-actions-server.yaml, .gitignore, src/main/java/com/swyp3/babpool/global/logging/MdcLoggingFilter.java
Resolves #없음
- URL 패턴에 asterisk를 사용한 경우 매칭이 안되는 문제
- `AntPathMatcher` 를 사용해 URL 패턴에 `*` 이 들어간 경우도 매칭시킬 수 있도록 해결
- 
---
=> fix: URL 패턴에 asterisk를 사용한 경우 매칭이 안되는 문제 해결

.github/workflows/github-actions-server.yaml, src/main/java/com/swyp3/babpool/domain/user/api/UserApi.java, src/main/java/com/swyp3/babpool/domain/user/application/UserService.java, src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java, src/main/java/com/swyp3/babpool/global/logging/MdcLoggingFilter.java, src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoTokenProvider.java, src/main/java/com/swyp3/babpool/infra/auth/service/AuthService.java, src/test/java/com/swyp3/babpool/global/logging/MdcLoggingFilterTest.java, src/test/java/com/swyp3/babpool/infra/auth/kakao/KakaoTokenProviderTest.java
- kakao redirect url 을 동적으로 변경하여 로컬환경에서 카카오 로그인이 안되는 이슈 해결
- 프론트 애플리케이션을 로컬환경에서 실행 후, 운영중인 백엔드 서버로 카카오 로그인을 요청할 경우, redirect url 이 로컬환경 url 으로 설정되어 있지 않아 카카오 로그인이 정상동작하지 않았습니다.
- http header 에 특정 key-value 를 담아 백엔드 서버로 요청할 경우, 동적으로 redirect url 을 로컬환경을 위한 url 으로 설정되도록 하여 이슈를 해결했습니다.
- 
---
=> fix(kakao): 로컬환경에서 카카오로그인이 안되는 이슈 해결

src/main/java/com/swyp3/babpool/global/logging/MdcLoggingFilter.java
- 로컬에서 카카오 로그인 요청 시, 리다이렉트 URL 을 변경하기 위한 커스텀 헤더 속성 반영
- "Origin" 헤더 속성에서 "x-babpool-local-front" 커스텀 헤더 속성을 사용하도록 변경했습니다.
- 'x-babpool-local-front' 헤더로 특정 값이 요청될 경우 'localhostFlag' 값을 'true' 으로 설정
- 로컬에서 요청했음을 확인하는데 사용된느 value는 코드레벨이 아닌 설정파일을 통해 세팅되도록 변경했습니다.
- 
---
=> update(filter): 커스텀 헤더 변경 반영

.github/workflows/github-actions-server.yaml, src/main/java/com/swyp3/babpool/global/config/JsonResponseLongToStringConfig.java, src/main/java/com/swyp3/babpool/global/swagger/SwaggerAccessInterceptor.java, src/main/java/com/swyp3/babpool/global/swagger/exception/SwaggerErrorCode.java, src/main/java/com/swyp3/babpool/global/swagger/exception/SwaggerException.java, src/main/java/com/swyp3/babpool/global/swagger/exception/SwaggerExceptionHandler.java
-  JSON 직렬화 및 스웨거 에러 응답 생성
- TSID 도입 후, 18자리의 긴 정수형 응답을 프론트에서 받을때, 뒤 2자리가 00으로 변경되는 문제를 해결하기 위해 JSON 으로 직렬화할 때 Long 타입을 String 타입으로 변환되도록 설정했습니다. 다음 링크를 참고하면 프론트에서도 위 문제를 해결할 수 있을 것으로 추정됩니다. [참고 링크](https://devpunch.tistory.com/27)
- 스웨거 접속 시 발생하는 에러를 처리하기 위한 커스텀예외 클래스, 에러코드 그리고 예외 발생 시 보여줄 응답을 추가했습니다.
- 스웨거 접속 시 보여지는 에러 페이지 샘플 입니다. 
---
=> feat: JSON 직렬화 및 스웨거 에러 응답 생성

.github/workflows/github-actions-server.yaml, src/main/java/com/swyp3/babpool/domain/possibledatetime/application/PossibleDateTimeServiceImpl.java, src/main/java/com/swyp3/babpool/domain/possibledatetime/dao/PossibleDateTimeRepository.java, src/main/resources/mapper/PossibleDateTimeMapper.xml, src/test/java/com/swyp3/babpool/domain/possibledatetime/dao/PossibleDateTimeRepositoryTest.java
- 일정 삭제 쿼리를 수행한 경우 `jdbc.UncategorizedSQLException: Error updating database.` 에러 발생.
- 일정 추가 쿼리를 수행할 때, 이미 존재하는 일정도 중복해 추가되는 문제 발생.
- 일정 삭제 쿼리
- MySQL에서 UPDATE & DELETE 를 할 때 자기 테이블의 데이터를 바로 사용하지 못한다. 따라서 서브쿼리를 사용하도록 변경
- 일정 추가 쿼리
- `WHERE NOT EXISTS` 구문을 사용
- 쿼리트 테스트 메서드 추가
- [DELETE에서의 서브쿼리 활용](https://velog.io/@khnn/TIL-DELETE%EC%97%90%EC%84%9C%EC%9D%98-%EC%84%9C%EB%B8%8C%EC%BF%BC%EB%A6%AC-%ED%99%9C%EC%9A%A9)
- 
---
=> fix(possibledatetime): 일정 추가/삭제 쿼리 수정

.github/workflows/github-actions-server.yaml, src/main/java/com/swyp3/babpool/domain/possibledatetime/application/PossibleDateTimeServiceImpl.java, src/main/java/com/swyp3/babpool/domain/possibledatetime/dao/PossibleDateTimeRepository.java, src/main/resources/mapper/PossibleDateTimeMapper.xml
- 기존 `updatePossibleDateTimeStatus` 매퍼는 일정 상태가 `AVAILABLE` 조건이 걸려 있어, `RESERVED` 상태의 일정을 변경하지 못하는 에러가 발생
- `updatePossibleDateTimeStatusFromAvailable` 를 별도로 생성하여 `AVAILABLE` 조건이 필요할 땐 해당 매퍼를 사용하고, `updatePossibleDateTimeStatus` 매퍼의 경우 일정 상태 조건을 제거함.
- 
---
=> hotfix: 일정 상태 변경 mapper 수정
