- build.gradle
- src/main/java/com/swyp3/babpool/global/util/jwt/JwtTokenizer.java
- src/main/java/com/swyp3/babpool/infra/redis/EmbeddedLocalRedisConfig.java
- src/main/java/com/swyp3/babpool/infra/redis/RedisRepositoryConfig.java
- src/main/java/com/swyp3/babpool/infra/redis/dao/TokenRedisRepository.java
- src/main/java/com/swyp3/babpool/infra/redis/domain/TokenForRedis.java
- src/test/java/com/swyp3/babpool/infra/redis/dao/TokenRedisRepositoryTest.java
Resolves #없음
- Redis 도입(로컬/테스트 환경)
1) 로컬 및 테스트 환경에서 Redis를 사용할 수 있도록 Embedded Redis를 적용했습니다.
- Embedded Redis를 적용한 당위성
1. 테스트는 개발 과정에서 매우 빈번하게 수행되어야 합니다. 때문에 수행 시간이 중요하다고 판단해 도커를 수행하는 TestContainer 대신 Embedded 방식을 선택했습니다.
2. 누가 오더라도 git clone 만 받으면 바로 로컬 개발/테스트를 시작할 수 있도록 하는 것을 지향해야 한다는 [향로님의 게시글](https://jojoldu.tistory.com/297)에 공감했습니다.
2) Redis를 위한 모듈을 추가함으로써 로깅 구현체가 자동으로 추가되어 다음과 같은 에러가 발생했습니다.
```
Exception in thread "main" java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.simple.SimpleLoggerFactory loaded from file:/**:/**/**/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/2.0.11/**/slf4j-simple-2.0.11.jar). If you are using WebLogic you …
```
> chore(redis): Add redis in local and test env to store whitelist jwt

- src/main/java/com/swyp3/babpool/infra/auth/AuthJwtParser.java
- src/main/java/com/swyp3/babpool/infra/auth/response/AuthMemberResponse.java
- @proHyundo 님의 의견을 반영
- deprecated 된 메소드 사용 지양
- @Notnull에 message 추가
- 
---
> fix: response jwt and add exception

- src/main/java/com/swyp3/babpool/infra/auth/exception/errorcode/AuthExceptionErrorCode.java
- src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoTokenProvider.java
- src/main/java/com/swyp3/babpool/infra/auth/request/LoginRequestDTO.java
- src/main/java/com/swyp3/babpool/infra/auth/service/AuthService.java
Resolves #26 
- 서버에서 카카오로부터 id Token을 받도록 수정
- KakaoTokenProvider 클래스 생성
- getIdTokenFromKakao 메서드 구현 
- 
---
> fix(auth): Get token from kakao

- .github/workflows/github-actions-server.yaml
- src/main/java/com/swyp3/babpool/global/config/CorsConfig.java
> Develop merge into main

- src/main/java/com/swyp3/babpool/domain/profile/api/ProfilePermitApi.java
- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfilePagingDto.java
- src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfilePagingResponse.java
- src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
- src/main/java/com/swyp3/babpool/domain/profile/domain/ProfileSortType.java
- src/main/resources/mapper/ProfileMapper.xml
Resolves #40 
- 프로필 페이징 결과 개선
프론트 개발자 @MintaekCho 님의 요청에 따라 아래 사항을 개선했습니다.
- 기존 상세 키워드 식별 값과, 상세 키워드 이름을 하나의 문자열로 합쳐 응답하던 형태에서, 상세 키워드 이름만 리스트로 변환해 응답에 포함하는 것으로 변경되었습니다.
- 검색어로 조회 하는 대상에 사용자 닉네임도 포함되었습니다.
- 응답 결과에 사용자 닉네임을 포함했습니다.
- 현재 프론트가 백엔드에게 요청 가능한 정렬 기준은 `Newest`, `Name` 입니다. 그 외 모든 값은 `Newest` 으로 변환되어 처리됩니다. 
- asc, desc 는 지정 가능합니다.
---
> refactor(profile): Update profile paging response (#40)

- src/main/java/com/swyp3/babpool/domain/profile/api/request/ProfileUpdateRequest.java
- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/profile/application/response/KeywordsResponse.java
- src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDetailDaoDto.java
- src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDetailResponse.java
- src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
- src/main/java/com/swyp3/babpool/domain/user/application/response/MyPageResponse.java
- src/main/java/com/swyp3/babpool/domain/user/application/response/MyPageUserDaoDto.java
- src/main/resources/mapper/ProfileMapper.xml
Resolves #없음
- keywords 리스트 응답을 문자열이 아닌 주제와 키워드를 명확히 알 수 있는 배열 형태로 반환 
- 변경 전
- 변경 후 
- 
---
> fix(profile): fix keywords response

- src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java
- src/main/java/com/swyp3/babpool/domain/profile/api/request/ProfileUpdateRequest.java
- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileUpdateResponse.java
- src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
- src/main/java/com/swyp3/babpool/domain/profile/domain/PossibleDate.java
- src/main/resources/mapper/ProfileMapper.xml
Resolves #52 
- 프로필 카드 수정 API 구현
- DB와의 Connection이 많이 일어나 성능에 문제가 있을 것 같습니다. 나중에 성능을 높이기 위한 리팩토링이 필요합니다.
- 
---
> feat: add profile update

- src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java
- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDefaultDaoDto.java
- src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDefaultResponse.java
- src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
- src/main/resources/mapper/ProfileMapper.xml
Resolves #54 
- 프로필 수정 페이지에 있는 사용자 기본 데이터 조회
- 
---
> feat: get profile update default date

- .github/workflows/github-actions-server.yaml
- src/main/java/com/swyp3/babpool/global/jwt/JwtTokenInterceptor.java
> fix(cors): Update jwt token interceptor to return true when options http method

- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDefaultResponse.java
- src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDetailResponse.java
- src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileKeywordsResponse.java
- src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
- src/main/java/com/swyp3/babpool/domain/profile/domain/ProfileDefault.java
- src/main/java/com/swyp3/babpool/domain/profile/domain/ProfileDetail.java
- src/main/java/com/swyp3/babpool/domain/user/application/response/MyPageResponse.java
- src/main/resources/mapper/ProfileMapper.xml
Resolves #50 
- 정한 규칙대로 메서드명과 클래스명 수정
- 레포지토리 메서드명 insert,get -> save, find로 수정
- ProfileDefaultDaoDto, ProfileDetailDaoDto -> ProfileDefault, ProfileDetail 
(응답 보내기 전 1차 데이터를 저장하기 위한 용도여서 클래스명도 수정하고 위치도 도메인으로 변경)
- 
---
> fix: Fix class and method name

- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDetailResponse.java
- src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/user/application/response/MyPageResponse.java
Resolves #62 
- @proHyundo 님이 구현해주신 메소드를 이용해 프로필 상세조회, 마이페이지 조회 응답에 리뷰 데이터와 밥약 히스토리 데이터를 추가하였습니다.
- 
- 
---
> feat: add review and appointment history data

- src/main/java/com/swyp3/babpool/domain/appointment/api/request/AppointmentCreateRequest.java
- src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentPossibleDateTimeResponse.java
- src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
- src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
- src/main/java/com/swyp3/babpool/global/jwt/JwtTokenInterceptor.java
- src/main/resources/mapper/AppointmentMapper.xml
- src/main/resources/mapper/ProfileMapper.xml
Resolves #없음
- 프로필 및 밥약 도메인에서 의도와 다르게 동작하거나 올바르게 동작하지 않은 코드 수정 
- 
- 
---
> refactor: Update profile and appoinment that isn't working correctly

- src/main/resources/mapper/AppointmentMapper.xml
Resolves #없음
- appointment mapper 의 foreach 문 문법 오류 해결
- open, close 속성을 제거했습니다.
- foreach 태그 위치를 변경했습니다.
> fix(appointment): Resolve mybatis foreach grammer in appointment mapper

- src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
- src/main/java/com/swyp3/babpool/domain/appointment/api/request/AppointmentAcceptRequest.java
- src/main/java/com/swyp3/babpool/domain/appointment/api/request/AppointmentCreateRequest.java
- src/main/java/com/swyp3/babpool/domain/appointment/api/request/AppointmentRejectRequest.java
- src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java
- src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentAcceptResponse.java
- src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentRejectResponse.java
- src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
- src/main/java/com/swyp3/babpool/domain/appointment/domain/AppointmentAcceptMessage.java
- src/main/java/com/swyp3/babpool/domain/appointment/domain/AppointmentRejectMessage.java
- src/main/java/com/swyp3/babpool/domain/appointment/exception/AppointmentException.java
- src/main/java/com/swyp3/babpool/domain/appointment/exception/errorcode/AppointmentErrorCode.java
- src/main/resources/mapper/AppointmentMapper.xml
Resolves #77 
- 밥약 수락 API 구현
- t_appointment 의 appointment_status와 possible_time_id를 업데이트 합니다.
- possible_time_id 삭제 관련 코드는 일단 주석처리 해놓았습니다.
- 참조키 문제 
- 
---
> feat: Accept appointment api

- src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
- src/main/resources/mapper/UserMapper.xml
- UserServiceImpl 에 @Transactional 추가
- user 테이블에는 정보가 있는데, profile 테이블에는 정보가 저장이 안되는 오류 발생
- @Transactional 적용으로 해결 
- 
---
> fix(user): add @Transactional

- src/main/java/com/swyp3/babpool/domain/user/api/UserApi.java
- src/main/java/com/swyp3/babpool/domain/user/application/UserService.java
- src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/user/application/response/UserGradeResponse.java
- src/main/java/com/swyp3/babpool/domain/user/dao/UserRepository.java
- src/main/resources/mapper/UserMapper.xml
- @MintaekCho 요청에 따라 사용자 구분 조회 API 구현
- 사용자 구분 조회 API 구현
- 
---
> Feat : get user grade api

- src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java
- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileRegistrationResponse.java
- src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
- src/main/resources/mapper/ProfileMapper.xml
Resolves #없음
- @MintaekCho 님 요청으로 프로필 등록 여부 API 구현
- 프로필 등록 여부를 register 필드에 담아 반환
- 
---
> feat: Add get profile active flag api

- src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java
- src/main/java/com/swyp3/babpool/domain/profile/api/request/ProfileUpdateRequest.java
- src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
Resolves #없음
- 프로필 수정 시 keywords 데이터 수정
- 키워드 식별자 값으로 데이터를 받으므로 List<String> -> List<Integer> 로 수정
- 
---
> fix: change ProfileUpdateRequest keywords data type

- .github/workflows/github-actions-server.yaml
- origin develop 에서 origin main 으로 병합 요청을 했더니, 충돌 발생.
- 충돌을 해결하기 위해 local develop 브랜치에서 origin main 을 pull 당겼으나 어떠한 충돌도 발생하지 않음.
- 최신 local main 브랜치에서 `conflict/version` 브랜치를 생성 후, `git merge develop` 수행.
- 이후, develop 으로 PR 생성
> fix(conflict): Already up to date

- src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentAcceptResponse.java
- src/main/java/com/swyp3/babpool/domain/appointment/application/response/appointmentdetail/AppointmentAcceptDetailResponse.java
- src/main/resources/mapper/AppointmentMapper.xml
Reverts swyp3-babpool/babpool-backend#127
> Revert "Fix: accept appointment api & get detail accept appointemtn api response"

- .github/workflows/github-actions-server.yaml
- src/main/java/com/swyp3/babpool/domain/possibledatetime/dao/PossibleDateTimeRepository.java
- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
- src/main/resources/mapper/PossibleDateTimeMapper.xml
> hotfix(possible-datetime): Update query and logic

- src/main/resources/mapper/AppointmentMapper.xml
Resolves #없음
- 쿼리 수정
- 
- 
---
> fix: query

- .github/workflows/github-actions-server.yaml
- src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/appointment/config/AppointmentWebSocketConfig.java
- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/profile/exception/errorcode/ProfileErrorCode.java
- src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
- src/main/java/com/swyp3/babpool/global/config/WebMvcInterceptJwtConfig.java
- src/main/java/com/swyp3/babpool/global/jwt/JwtTokenizer.java
- src/main/java/com/swyp3/babpool/global/jwt/application/JwtService.java
- src/main/java/com/swyp3/babpool/global/jwt/application/JwtServiceImpl.java
- src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckApi.java
> release: Merge hotfix/proHyundo into main

- .github/workflows/github-actions-server.yaml
- src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
Resolves #없음
- 밥약 상세 조회 시 상대방 데이터가 보이도록 수정
- 밥약 상세 조회 시 상대방 데이터가 보이도록 수정
- 
---
> Fix: 밥약 상세 조회 시 상대방 데이터가 보이도록 수정

- src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
- src/main/java/com/swyp3/babpool/domain/review/api/request/ReviewCreateRequest.java
- src/main/java/com/swyp3/babpool/domain/review/application/ReviewServiceImpl.java
- src/main/resources/mapper/AppointmentMapper.xml
> Hotfix/review: 리뷰 생성 시 appointment_status 값 변경

- .github/workflows/github-actions-server.yaml
- src/main/java/com/swyp3/babpool/domain/appointment/config/AppointmentWebSocketConfig.java
Resolves #없음
- `jxy.me` 사이트에서 소켓 통신 테스트를 할 경우 CORS 오류가 발생
- `jxy.me` 사이트에서 소켓 통신 테스트를 위해 setAllowedOrigins 추가
---
> cors: Update set allowed origins for websocket add jxy.me

- .github/workflows/github-actions-server.yaml
- src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
- src/main/java/com/swyp3/babpool/global/jwt/application/JwtServiceImpl.java
- src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckStompAPi.java
> release: Merge develop into main, to apply convertandsend to useruuid instead profileid

- .github/workflows/github-actions-server.yaml
- .gitignore
- src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoTokenProvider.java
- 카카오 리다이렉트 url 을 동적으로 변경될 수 있도록 재수정
- 지난 release 에서 리다이렉트 url 을 동적으로 변경될 수 있도록 수정했었으나, 싱글톤 객체의 property가 수정되도록 로직을 작성하여 문제가 발생함.
- 로컬 변수를 생성해 멤버 변수의 값은 변경되지 않도록 재수정 함.
- 
---
> hotfix(kakao): 카카오 리다이렉트 url 이슈 해결

- build.gradle
- src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
- src/main/java/com/swyp3/babpool/global/config/SwaggerConfig.java
- src/main/java/com/swyp3/babpool/global/config/WebMvcInterceptJwtConfig.java
- src/main/java/com/swyp3/babpool/global/config/swagger/SwaggerAccessInterceptor.java
- src/main/java/com/swyp3/babpool/global/jwt/JwtTokenizer.java
- src/main/java/com/swyp3/babpool/global/jwt/api/JwtApiPermitted.java
- src/main/java/com/swyp3/babpool/global/jwt/application/JwtServiceImpl.java
- src/main/java/com/swyp3/babpool/global/swagger/SwaggerAccessInterceptor.java
- src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckApi.java
- API 문서 생성을 위해 Swagger를 도입했습니다.
- ADMIN 권한을 가진 사용자만 스웨거 URL에 접근할 수 있도록 Interceptor를 생성했습니다.
- ADMIN 권한을 가진 사용자가 토큰을 요청할 경우 기존 15분에서 연장한 7일의 만료기한을 가진 토큰을 발급하도록 변경했습니다.
- 
---
> feat(swagger): 스웨거 도입

- .github/workflows/github-actions-server.yaml
- src/main/java/com/swyp3/babpool/domain/appointment/api/request/AppointmentCreateRequest.java
- src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/possibledatetime/api/PossibleDateTimeApi.java
- src/main/java/com/swyp3/babpool/domain/possibledatetime/api/request/PossibleDateTimeUpdateRequest.java
- src/main/java/com/swyp3/babpool/domain/possibledatetime/application/PossibleDateTimeService.java
- src/main/java/com/swyp3/babpool/domain/possibledatetime/application/PossibleDateTimeServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/possibledatetime/application/response/PossibleDateTimeResponse.java
- src/main/java/com/swyp3/babpool/domain/possibledatetime/dao/PossibleDateTimeRepository.java
- src/main/java/com/swyp3/babpool/domain/possibledatetime/exception/handler/PossibleDateTimeExceptionHandler.java
- src/main/java/com/swyp3/babpool/global/logging/ClientIPResolver.java
- src/main/resources/mapper/AppointmentMapper.xml
- src/main/resources/mapper/PossibleDateTimeMapper.xml
- src/test/java/com/swyp3/babpool/domain/appointment/api/AppointmentApiTest.java
- src/test/java/com/swyp3/babpool/domain/possibledatetime/application/PossibleDateTimeServiceImplTest.java
- src/test/java/com/swyp3/babpool/domain/possibledatetime/dao/PossibleDateTimeRepositoryTest.java
- src/test/java/com/swyp3/babpool/global/logging/ClientIPResolverTest.java
- src/test/java/com/swyp3/babpool/global/logging/MdcLoggingFilterTest.java
> fix(appointment): 약속 생성이 되지 않은 문제를 해결

- .github/workflows/github-actions-server.yaml
- src/main/resources/mapper/PossibleDateTimeMapper.xml
- 다음 Request 요청 시, 아래와 같은 SQL 오류가 발생
```
"
CAST('2024-08-06 17:00:00' AS TIMESTA' at line 5
CAST('2024-08-06 17:00:00' AS TIMESTA' at line 5
; bad SQL grammar []"
```
- MySQL에서 CAST 함수를 사용 시, 허용되지 않는 Type을 수정
- 
---
> hotfix(possibledatetime): CAST 함수 사용시 MySQL에서 지원하는 Type으로 변경

- .github/workflows/github-actions-server.yaml
- src/main/java/com/swyp3/babpool/domain/possibledatetime/dao/PossibleDateTimeRepository.java
- src/main/resources/mapper/PossibleDateTimeMapper.xml
- src/test/java/com/swyp3/babpool/domain/possibledatetime/dao/PossibleDateTimeRepositoryTest.java
- H2 데이터베이스와 MySQL 문법 호환 문제로 테스트 1개가 실패함
- 임시로 H2 전용 매퍼를 생성하여 해결
- 추후 H2 Embeded를 제거하고 MySQL 컨테이너로 테스트를 수행하는 것을 고려해볼 것.
- 
---
> test(possibledatetime): H2, MySQL 문법 호환 문제 해결

- .github/workflows/github-actions-server.yaml
- src/main/java/com/swyp3/babpool/domain/appointment/api/request/AppointmentAcceptRequest.java
> update(appointment): 밥 약속 수락 요청 dto 에서 불필요한 시간 id 제거

- .github/workflows/github-actions-server.yaml
- src/main/resources/mapper/AppointmentMapper.xml
> fix: 마이바티스 데이터바인딩

- .github/workflows/github-actions-server.yaml
- src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
- src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/appointment/exception/errorcode/AppointmentErrorCode.java
- src/main/resources/mapper/AppointmentMapper.xml
1. 밥 약속 신청 시, 과거 일정에 신청하는 경우에 대한 유효성 검증이 누락됨
2. 요청 받은 밥 약속 목록 조회 시, 확정된 일정임에도 날짜및시간 데이터가 null 값이 응답됨
1. 유효성 검증을 추가 하여 아래에 해당하는 경우, BAD_REQUEST 에러 응답을 내리도록 추가
- 현재 시간보다 과거 일정에 요청할 경우
- 요청하는 시간의 포맷이 00분 00초 가 아닌 경우
- 기획 요구사항에 따른 시간 범위를 벗어난 경우
2. sql mapper 에 'ACCEPT' 를 'ACCEPTED' 으로 변경하여 해결
- 요청 가능한 시간대가 변경될 수 있기 때문에 yml 파일로 시간 범위를 관리하는 것이 더 좋아 보임.
---
> Fix/appointment: API 오류/검증 개선

- .github/workflows/github-actions-server.yaml
- src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/possibledatetime/application/PossibleDateTimeService.java
- src/main/java/com/swyp3/babpool/domain/possibledatetime/application/PossibleDateTimeServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
- src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
- src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
- src/main/java/com/swyp3/babpool/domain/profile/exception/errorcode/ProfileErrorCode.java
- src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
1. 약속 취소 시, 요청했던 일정이 AVAILABLE 으로 변경되지 않음.
2. 소셜 로그인 시, 소셜 서비스에서 사용중인 프로필 이미지로 변경되지 않음.
- 1) 약속 취소 API
- 일정의 상태를 변경하는 서비스 메서드를 추가함
- 2) 프로필 이미지 변경
- 사용자가 임의로 프로필 이미지를 변경한 경우가 아니라면, 소셜 서비스로부터 제공받은 프로필 이미지 URL 으로 데이터를 변경하도록 수정
- 
---
> fix: API 개선
